CREATE TABLE IF NOT EXISTS device (
  device_id INT AUTO_INCREMENT PRIMARY KEY,
  device_sl VARCHAR(255) NOT NULL,
  device_name VARCHAR(255) NOT NULL,
  device_category VARCHAR(255) NOT NULL,
  device_req_date DATE NOT NULL,
  remark VARCHAR(255),
  status VARCHAR(255) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(255) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS person (
  person_id INT AUTO_INCREMENT PRIMARY KEY,
  person_sl VARCHAR(255) NOT NULL,
  person_email VARCHAR(255) NOT NULL,
  person_name VARCHAR(255) NOT NULL,
  person_team VARCHAR(255),
  status VARCHAR(255) NOT NULL DEFAULT 'active',
  remark VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(255) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_by VARCHAR(255) NOT NULL
);

